In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [19]:
data=np.loadtxt("training_ccpp_x_y_train.csv",delimiter=",")
data1=pd.DataFrame(data)
# print(data.shape)
X=data[:,:-1]
Y=data[:,-1]
print(X)
# print(Y)
scaler=preprocessing.StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
print(X)


[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]
[[-1.47827466e+00 -1.24764165e+00  1.30221067e+00  7.58624590e-01]
 [ 2.89012041e-01  3.06797549e-01  6.61749044e-01 -4.46921842e-01]
 [-3.99975582e-01 -4.21012529e-01 -2.87207194e-01  3.75010552e-01]
 ...
 [ 1.36062192e+00  1.18048335e+00 -6.54382840e-01 -5.83682640e-01]
 [-4.36097263e-01  9.29089763e-04  7.84140927e-01 -6.59584883e-01]
 [ 1.40209496e+00  6.07960340e-01 -4.31394890e-01 -1.73110573e+00]]


In [21]:
def gradient_descent(X,Y,learning_rate,m):
    m_slope=np.zeros(len(X[0]))
    M=len(X)
    for i in range(len(X)):
        x=X[i]
        y=Y[i]
        for j in range(len(x)):
            m_slope[j]+=(-2/M)*(y-((m*x).sum()))*x[j]
#             print(m_slope)
    new_slope=m-(learning_rate*m_slope)
    return new_slope
# THE GRADIENT DESCENT FUNCTION PERFORMS GRADIENT DESCENT ON EACH DATA ROW BY MAKING AN ARRAY AND ALL THE SLOPES ARE SAVED INSIDE 
# THESE ARRAY WHICH IS USED AT LAST TO UPDATED BY LEARNING RATE AND RETURNED

In [22]:
def gd(X_points,Y_points,learning_rate,num_iterations):
    m=np.array([0 for i in range(len(X_points[0]))])
#     this is a way to make numpy array and fill all the values in it to a specific value
    for i in range(num_iterations):
        m=gradient_descent(X_points,Y_points,learning_rate,m)
#         print(m)
        print(i,": Cost:",cost(X_points,Y_points,m))
    return m

In [23]:
# THE COST FUNCTION TO CALCULATE THE COST TO SEE HOW ARE WE DOING IN TERMS OF OUR m

def cost(X,Y,m):
    M=len(X)
    cost=0
    for i in range(len(X)):
        x=X[i]
        y=Y[i]
        cost+=(1/M)*((y-((m*x).sum()))**2)
    
    return cost

In [24]:
def run(x,y):
    print(x)
    print(x.shape)
    x=np.append(x, np.ones(len(x)).reshape(-1, 1), axis=1)
    print(x.shape)
    
#     learning_rate=0.01
#     num_iterations=500
#     for above lr and iterations we get the last cost as: 17.124078149330174
    learning_rate=0.1
    num_iterations=300
    m=gd(x,y,learning_rate,num_iterations)
    return m
    

In [25]:
m=run(X,Y)

[[-1.47827466e+00 -1.24764165e+00  1.30221067e+00  7.58624590e-01]
 [ 2.89012041e-01  3.06797549e-01  6.61749044e-01 -4.46921842e-01]
 [-3.99975582e-01 -4.21012529e-01 -2.87207194e-01  3.75010552e-01]
 ...
 [ 1.36062192e+00  1.18048335e+00 -6.54382840e-01 -5.83682640e-01]
 [-4.36097263e-01  9.29089763e-04  7.84140927e-01 -6.59584883e-01]
 [ 1.40209496e+00  6.07960340e-01 -4.31394890e-01 -1.73110573e+00]]
(7176, 4)
(7176, 5)
0 : Cost: 132273.17028197853
1 : Cost: 84643.21738144128
2 : Cost: 54177.474227792685
3 : Cost: 34683.656935452964
4 : Cost: 22208.479529620818
5 : Cost: 14224.382169986968
6 : Cost: 9114.383468776608
7 : Cost: 5843.781284088756
8 : Cost: 3750.4051743364307
9 : Cost: 2410.4727339052597
10 : Cost: 1552.762193756394
11 : Cost: 1003.6891423474597
12 : Cost: 652.1571417929908
13 : Cost: 427.06242464503333
14 : Cost: 282.8969056987255
15 : Cost: 190.5340535532469
16 : Cost: 131.33178845157047
17 : Cost: 93.35828546206275
18 : Cost: 68.97644681535036
19 : Cost: 53.2979309

258 : Cost: 20.912007401939192
259 : Cost: 20.9119969905073
260 : Cost: 20.911986998553033
261 : Cost: 20.91197740917572
262 : Cost: 20.91196820615533
263 : Cost: 20.91195937392587
264 : Cost: 20.911950897547612
265 : Cost: 20.911942762683687
266 : Cost: 20.911934955574154
267 : Cost: 20.91192746301402
268 : Cost: 20.911920272329922
269 : Cost: 20.911913371359102
270 : Cost: 20.91190674842922
271 : Cost: 20.91190039233786
272 : Cost: 20.911894292334136
273 : Cost: 20.911888438100082
274 : Cost: 20.911882819733943
275 : Cost: 20.911877427732225
276 : Cost: 20.911872252974884
277 : Cost: 20.911867286708997
278 : Cost: 20.911862520534548
279 : Cost: 20.911857946389727
280 : Cost: 20.911853556537633
281 : Cost: 20.911849343553385
282 : Cost: 20.911845300310457
283 : Cost: 20.91184141997034
284 : Cost: 20.911837695969606
285 : Cost: 20.911834122009136
286 : Cost: 20.91183069204394
287 : Cost: 20.911827400272387
288 : Cost: 20.911824241126645
289 : Cost: 20.911821209263287
290 : Cost: 20.911

PREDICTIONS

In [26]:
print(m.shape)

(5,)


In [28]:
print(Y.shape)

(7176,)


In [33]:
x=np.loadtxt("test_ccpp_x_test.csv",delimiter=",")
print(x.shape)
x=scaler.transform(x)
print(x)
x=np.append(x,np.ones(len(x)).reshape(-1,1),axis=1)
print(x)

(2392, 4)
[[-1.02742256 -0.96138014  0.72378329  1.20446479]
 [-1.01136848 -1.25783726 -0.09942787  0.57331371]
 [ 0.97398614  1.62360048 -1.27807846  0.39005424]
 ...
 [ 0.62748557  0.93814142 -0.69965107  1.27284519]
 [ 0.51644485 -0.90099073  0.11685368 -0.54470581]
 [ 0.28499852  0.46914312  0.95515424  0.80580707]]
[[-1.02742256 -0.96138014  0.72378329  1.20446479  1.        ]
 [-1.01136848 -1.25783726 -0.09942787  0.57331371  1.        ]
 [ 0.97398614  1.62360048 -1.27807846  0.39005424  1.        ]
 ...
 [ 0.62748557  0.93814142 -0.69965107  1.27284519  1.        ]
 [ 0.51644485 -0.90099073  0.11685368 -0.54470581  1.        ]
 [ 0.28499852  0.46914312  0.95515424  0.80580707  1.        ]]


In [34]:
def predict(x,m):
    y=np.zeros(len(x))
    for i in range(len(x)):
        y[i]=(m*x[i]).sum()
    print(y)    
    return y


In [35]:
y=predict(x,m)

[469.96064166 471.76779619 433.85082252 ... 439.14235715 450.6764549
 447.27913239]


In [36]:
print(y)

[469.96064166 471.76779619 433.85082252 ... 439.14235715 450.6764549
 447.27913239]


In [37]:
np.savetxt(X=y,fname="Predictions3.csv",delimiter=",",fmt='%.5f')